version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1
    groups:
      c2pa:
        patterns:
          - "c2pa"
      other-crates:
        patterns:
          - "*"
        exclude-patterns:
          - "c2pa"
    open-pull-requests-limit: 10
