version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/examples/cli"
      - "/examples/azure_function"
      - "/examples/keda-blob-storage"
      - "/lib"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
