[workspace]
resolver = "2"

members = [
    "lib",
    "examples/cli",
    "examples/azure_function",
    "examples/keda-blob-storage",
]

[workspace.package]
version = "0.90.4"

[workspace.dependencies]
anyhow = { version = "1.0.104", features = ["backtrace"] }
async-trait = "0.1.91"
azure_core = "1.1.0"
azure_identity = "1.0.0"
env_logger = "0.11.11"
futures = "0.3.33"
log = "0.4.33"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "macros",
    "io-util",
] }
c2pa = { version = "0.90.4", features = [
    "add_thumbnails",
    "file_io",
    "fetch_remote_manifests",
    "http_reqwest"
], default-features = false }
