[package]
name = "function"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.94", features = ["backtrace"] }
azure_core = "0.23.0"
azure_identity = "0.23.0"
c2pa-acs = { path = "../lib" }
env_logger = "0.11.5"
futures = "0.3.31"
log = "0.4.22"
tempfile = "3.14.0"
tokio = { version = "1.44.2", features= ["rt", "rt-multi-thread", "macros"] }
warp = "0.3.7"
