[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.94", features = ["backtrace"] }
azure_identity = "0.21.0"
c2pa-acs = { path = "../lib" }
clap_derive = "4.5.18"
clap= { version = "4.5.22", features = ["derive"] }
env_logger = "0.11.5"
tokio = { version = "1.42.0", features= ["rt", "rt-multi-thread", "macros"] }
c2pa = "0.39.0"
azure_core = "0.21.0"
log = "0.4.22"
